version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: /start-dev.sh
    ports:
      - "1337:1337"
    environment:
      - POSTGRES_USER=test_project
      - USE_DOCKER=yes
    depends_on:
      - postgres
    volumes:
      - .:/app
    links:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=test_project

  # frontend:
  #   stdin_open: true
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
