version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - .:/server
  frontend:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
