version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tye_db
    depends_on:
      - db

  db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
