version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./server:/backend
    command: sails lift
  frontend:
    stdin_open: true
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/react-app/src
      - ./client/public:/react-app/public
    links:
      - backend
    command: npm run start
